name: Playwright Tests
on:
  push:
    branches: [  main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        node-version: lts/*
